try {
  throw new Error('Ha ocurrido algo malo :(');
} catch (error) {
  console.log(error);
}
